(()=>{'use strict';
const PIXEL='341131507668987';
const KEEP=['utm_source','utm_medium','utm_campaign','utm_content','utm_term','fbclid'];
const CHECKOUT='';
const TESTIMONIALS=['https://static.wixstatic.com/media/279a76_a2da35cf7c034534bd3dd8a35b6bb533~mv2.jpeg','https://static.wixstatic.com/media/279a76_31b7a1cc048e484aaa617ef5f0f46342~mv2.jpeg','https://static.wixstatic.com/media/279a76_65cb56988a414e4ab046c28d73df92f1~mv2.jpeg','https://static.wixstatic.com/media/279a76_3751faff93864c399da5f65ec64f6c72~mv2.jpeg','https://static.wixstatic.com/media/279a76_0c587d22bcac4156bf9b886f3b7d45e0~mv2.jpeg','https://static.wixstatic.com/media/279a76_01d550d213794f1da5a6d6b66b5da8bf~mv2.jpeg','https://static.wixstatic.com/media/279a76_650db30af46a413486334b760df661ca~mv2.jpg','https://static.wixstatic.com/media/279a76_a6d49d97e35a4685a3ce1ed947890ef9~mv2.jpg'];
let pixelLoaded=false;
function track(name,data={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...data});try{if(window.fbq)fbq('trackCustom',name,data)}catch(e){}}
function loadPixel(){if(pixelLoaded)return;pixelLoaded=true;!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init',PIXEL);fbq('track','PageView');fbq('track','ViewContent',{content_name:'Livro Bypass Neural',content_type:'product',value:17,currency:'BRL'})}
function consent(){const c=document.getElementById('cookie'),v=localStorage.getItem('lbn_cookie');if(v==='accepted')loadPixel();else if(!v)c.style.display='block';document.getElementById('accept')?.addEventListener('click',()=>{localStorage.setItem('lbn_cookie','accepted');c.style.display='none';loadPixel()});document.getElementById('reject')?.addEventListener('click',()=>{localStorage.setItem('lbn_cookie','rejected');c.style.display='none'})}
function captureParams(){const q=new URLSearchParams(location.search),saved={};KEEP.forEach(k=>{if(q.get(k))saved[k]=q.get(k)});if(Object.keys(saved).length)sessionStorage.setItem('lbn_acq',JSON.stringify(saved));return saved}
function decorate(url){const u=new URL(url,location.href);let p={};try{p=JSON.parse(sessionStorage.getItem('lbn_acq')||'{}')}catch(e){}KEEP.forEach(k=>{if(p[k])u.searchParams.set(k,p[k])});return u.toString()}
function buying(){const modal=document.getElementById('buyModal');document.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>{const loc=b.dataset.location||'unknown';track('LBN17_CTA_Click',{location:loc,value:17,currency:'BRL'});if(CHECKOUT){track('InitiateCheckout',{content_name:'Livro Bypass Neural',value:17,currency:'BRL'});location.href=decorate(CHECKOUT)}else modal.hidden=false}));document.getElementById('modalClose')?.addEventListener('click',()=>modal.hidden=true);document.getElementById('modalOk')?.addEventListener('click',()=>modal.hidden=true);modal?.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true})}
function testimonials(){const g=document.getElementById('testimonials');if(!g)return;TESTIMONIALS.forEach((src,i)=>{const b=document.createElement('button');b.type='button';b.className='testimonial';b.dataset.src=src;b.setAttribute('aria-label',`Ampliar relato ${i+1}`);b.innerHTML=`<img src="${src}" loading="lazy" decoding="async" alt="Relato original ${i+1}">`;g.appendChild(b)});g.addEventListener('click',e=>{const b=e.target.closest('.testimonial');if(!b)return;document.getElementById('lbImg').src=b.dataset.src;document.getElementById('lightbox').classList.add('open');track('LBN17_Testimonial_Open',{index:[...g.children].indexOf(b)+1})})}
function lightbox(){const lb=document.getElementById('lightbox');document.getElementById('lbClose')?.addEventListener('click',()=>lb.classList.remove('open'));lb?.addEventListener('click',e=>{if(e.target===lb)lb.classList.remove('open')})}
function progress(){const bar=document.getElementById('progressBar'),sticky=document.getElementById('stickyBuy');function tick(){const d=document.documentElement,den=d.scrollHeight-innerHeight,p=den>0?scrollY/den:0;bar.style.width=`${Math.max(0,Math.min(1,p))*100}%`;sticky.classList.toggle('show',p>.12&&p<.94)}tick();addEventListener('scroll',tick,{passive:true});addEventListener('resize',tick)}
function reveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const els=[...document.querySelectorAll('.reveal')];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});els.forEach(el=>io.observe(el))}
function observers(){[['#quiz','LBN17_Diagnostic_View'],['#conteudo','LBN17_ChapterSection_View'],['#prova','LBN17_Testimonials_View'],['#oferta','LBN17_Offer_View']].forEach(([sel,ev])=>{const el=document.querySelector(sel);if(!el)return;let done=false;new IntersectionObserver(es=>{if(!done&&es.some(x=>x.isIntersecting)){done=true;track(ev)}},{threshold:.25}).observe(el)})}
function quiz(){const shell=document.getElementById('quiz');if(!shell)return;const questions=[{q:'Em qual momento suas conversas mais costumam perder força?',opts:[['diagnostico','Antes da proposta, quando preciso entender melhor o cliente'],['valor','Quando apresento valor ou chego ao preço'],['objecao','Quando aparece “tá caro”, “vou pensar” ou outra objeção'],['fechamento','No final, quando preciso definir decisão ou próximo passo']]},{q:'Quando a conversa trava, qual é sua reação mais comum?',opts:[['diagnostico','Explico a solução cedo demais'],['valor','Acrescento argumentos ou justifico o preço'],['objecao','Respondo rápido para não perder a venda'],['fechamento','Deixo aberto e espero a pessoa voltar']]},{q:'O que você mais gostaria de melhorar primeiro?',opts:[['diagnostico','Perguntar melhor antes de apresentar'],['valor','Conectar valor ao que o cliente realmente quer'],['objecao','Entender objeções antes de responder'],['fechamento','Terminar com sim, não ou próximo passo claro']]}];
const labels={diagnostico:['DIAGNÓSTICO FRACO','Seu sinal principal está antes da proposta. O livro ajuda a desacelerar a apresentação, organizar contexto e usar perguntas para entender melhor antes de oferecer.'],valor:['VALOR DIFUSO','Seu sinal principal aparece quando a solução precisa fazer sentido para o problema. O livro trabalha congruência entre diagnóstico, proposta, valor e preço.'],objecao:['OBJEÇÃO REATIVA','Seu sinal principal está na resposta rápida. O livro ensina a acolher, precisar e confirmar a objeção antes de responder ao ponto real.'],fechamento:['FECHAMENTO ABERTO','Seu sinal principal está no fim da conversa. O livro ajuda a transformar finais vagos em decisão ou próximo passo explícito.']};
let step=0,answers=[];const qEl=document.getElementById('quizQuestion'),oEl=document.getElementById('quizOptions'),sEl=document.getElementById('quizStep'),rEl=document.getElementById('quizResult');function render(){if(step>=questions.length){const count={diagnostico:0,valor:0,objecao:0,fechamento:0};answers.forEach(a=>count[a]++);const priority=['diagnostico','valor','objecao','fechamento'];const top=priority.sort((a,b)=>count[b]-count[a])[0],res=labels[top];qEl.textContent='Seu sinal mais provável nesta leitura:';oEl.innerHTML='';sEl.textContent='RESULTADO';rEl.innerHTML=`<b>${res[0]}</b><p>${res[1]}</p><div style="margin-top:14px"><button class="btn btn-gold" data-buy data-location="diagnostic_result">QUERO APROFUNDAR ISSO NO LIVRO — R$17</button></div>`;rEl.classList.add('show');rEl.querySelector('[data-buy]').addEventListener('click',()=>{track('LBN17_CTA_Click',{location:'diagnostic_result',value:17,currency:'BRL'});const modal=document.getElementById('buyModal');if(CHECKOUT)location.href=decorate(CHECKOUT);else modal.hidden=false});track('LBN17_Diagnostic_Complete',{result:top,answers:answers.join('|')});return}const item=questions[step];qEl.textContent=item.q;sEl.textContent=`${step+1}/${questions.length}`;oEl.innerHTML='';item.opts.forEach(([key,text])=>{const b=document.createElement('button');b.type='button';b.className='quiz-option';b.textContent=text;b.addEventListener('click',()=>{answers.push(key);track('LBN17_Diagnostic_Answer',{step:step+1,answer:key});step++;render()});oEl.appendChild(b)})}render()}
function faqTracking(){document.querySelectorAll('.faq details').forEach((d,i)=>d.addEventListener('toggle',()=>{if(d.open)track('LBN17_FAQ_Open',{index:i+1})}))}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('lightbox')?.classList.remove('open');const modal=document.getElementById('buyModal');if(modal)modal.hidden=true}});
document.addEventListener('DOMContentLoaded',()=>{captureParams();consent();buying();testimonials();lightbox();progress();reveal();observers();quiz();faqTracking();track('LBN17_PageReady',{query:location.search})});
})();